public enum ButtonAction {
  START,SETTINGS,NETWORK,PAUSE,RESUME,DROPDOWN,SELECT,DRAG,ABOUT, EXIT,ZOOMIN,ZOOMOUT
  ,BACK, AUTOZOOM,MAINMENU,GAME,SELSERVER,SELCLI,SELCUS,SELSOC,VIEW, READY_P,INPUT,CONSOLE,CONSOLE1
}